### ISSUE TITLE
🏗 Reconciliation frequency configuration via annotations

### ISSUE THREAD

**Issue by TylerGillson** [validator-labs/validator#358]
### Summary

Today, all validator plugin custom resources are re-reconciled every 2m. This value should be configurable.

**Comment by ADorigi** [comment]
Hi @TylerGillson, I would be willing to work on this issue.

**Comment by TylerGillson** [comment]
Hey @ADorigi. That would be fantastic! Contributions are very welcome. Let me know if you have any questions about how to get started. This epic requires a PR for all official plugins.

**Comment by ADorigi** [comment]
Thank you @TylerGillson 

I will be starting with the `validator-plugin-oci` plugin and working towards the other plugins.

After addition of the annotation, a simple resource definition of kind `OciValidator` would look like:
```
apiVersion: validation.spectrocloud.labs/v1alpha1
kind: OciValidator
metadata:
  name: ocivalidator-sample-public-oci-registries
  namespace: validator
  annotations:
    reconciliation-frequency: "120"
spec:
  ociRegistryRules:
    - name: "public oci registry with tag"
      host: "docker.io"
      validationType: "none" 
      artifacts:
        - ref: "library/redis:7.2.4"
```

I have taken the following points into consideration:
- The annotation's key is `reconciliation-frequency`. Let me know if there should be a specific DNS subdomain as the prefix for the key. 
- The value is in seconds

I will be working towards implementing the above. Please advise if the approach needs to be modified.
